version: "3.8"
services:
  backend-flask:
    environment:
      FRONTEND_URL: "https://3001-${GITPOD_WORKSPACE_ID}.${GITPOD_CLUSTER_HOST}"
      BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_CLUSTER_HOST}"
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
  
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_CLUSTER_HOST}"
    build:
      context: ./frontend-react-js
      dockerfile: Dockerfile
    volumes:
      - ./frontend-react-js:/frontend-react-js

networks:
  internal-network:
    driver: bridge
    name: cruddur